from pathlib import Path
import re

path = Path('T-Display-S3/src/display_ui.cpp')
text = path.read_text()


def replace(pattern, repl, name):
    global text
    text, count = re.subn(pattern, repl, text, count=1, flags=re.S)
    if count != 1:
        raise SystemExit(f'{name}: expected one replacement, got {count}')

replace(
    r'''static void drawLandscapeMetricCard\(int x, int y, int w, int h,\n                                    const String &label, const String &value\) \{.*?\n\}\n\nvoid drawForecastHighLowCard\(\)''',
    '''static void drawLandscapeMetricCard(int x, int y, int w, int h,\n                                    const String &label, const String &value) {\n  const uint16_t cyan = rgb565(132, 211, 255);\n  drawConceptCard(x, y, w, h, 7, false);\n\n  display.setTextDatum(textdatum_t::middle_center);\n  display.setFont(&fonts::Font0);\n  display.setTextSize(label.length() > 9 ? 0.62f : 0.70f);\n  drawBoldText(label, x + w / 2, y + 10, cyan);\n  display.setTextSize(1.0f);\n\n  display.setFont(&fonts::Font4);\n  if (display.textWidth(value) > w - 8) {\n    display.setFont(&fonts::Font2);\n  }\n  drawBoldText(value, x + w / 2, y + 33, C_WHITE);\n}\n\nvoid drawForecastHighLowCard()''',
    'metric card')

replace(
    r'''void drawForecastHighLowCard\(\) \{.*?\n\}\n\nvoid drawHeader\(\)''',
    '''void drawForecastHighLowCard() {\n  if (waitingScreenActive || !detailsPageActive || !wx.valid) return;\n\n  const bool tomorrow = forecastShowsTomorrow();\n  String highText = "--";\n  String lowText = "--";\n  if (wx.forecastValid) {\n    const float high = tomorrow ? wx.forecastTomorrowHighF : wx.forecastTodayHighF;\n    const float low = tomorrow ? wx.forecastTomorrowLowF : wx.forecastTodayLowF;\n    if (isfinite(high)) highText = String((int)lroundf(high)) + String("\\xB0");\n    if (isfinite(low)) lowText = String((int)lroundf(low)) + String("\\xB0");\n  }\n\n  drawLandscapeMetricCard(160, 79, 75, 51,\n                          tomorrow ? "TMRW HIGH" : "TODAY HIGH", highText);\n  drawLandscapeMetricCard(238, 79, 78, 51,\n                          tomorrow ? "TMRW LOW" : "TODAY LOW", lowText);\n}\n\nvoid drawHeader()''',
    'forecast cards')

replace(
    r'''void drawHeader\(\) \{.*?\n\}\n\nstatic void drawLandscapeStatusBar''',
    '''void drawHeader() {\n  String station = cfg.stationName.length() ? cfg.stationName : "Weather Station";\n  if (station.length() > 16) station = station.substring(0, 16);\n\n  drawConceptCard(4, 4, 312, 22, 6, true);\n  display.setTextDatum(textdatum_t::middle_left);\n  display.setFont(&fonts::Font2);\n  drawBoldText(station, 10, 15, C_WHITE);\n\n  display.setTextDatum(textdatum_t::middle_right);\n  display.setFont(&fonts::Font0);\n  display.setTextSize(0.78f);\n  display.setTextColor(rgb565(231, 241, 247));\n  display.drawString(currentDateText(), 309, 15);\n  display.setTextSize(1.0f);\n}\n\nstatic void drawLandscapeStatusBar''',
    'header')

replace(
    r'''static void drawLandscapeStatusBar\(const char \*buttonHint\) \{.*?\n\}\n\nvoid drawFooter\(\)''',
    '''static void drawLandscapeStatusBar(const char *buttonHint) {\n  const uint16_t muted = rgb565(185, 211, 226);\n  const uint16_t green = rgb565(117, 237, 79);\n  const uint16_t red = rgb565(255, 122, 103);\n  const uint16_t border = rgb565(28, 91, 124);\n\n  display.fillRect(0, 133, 320, 37, C_BLACK);\n  display.drawFastHLine(4, 134, 312, border);\n\n  String left;\n  String state;\n  uint16_t stateColor = green;\n\n  if (WiFi.status() != WL_CONNECTED) {\n    if (setupApStarted) {\n      left = "Setup 192.168.4.1";\n      state = "SETUP";\n    } else {\n      left = "Wi-Fi disconnected";\n      state = "OFFLINE";\n    }\n    stateColor = red;\n  } else if (!apiConfigured()) {\n    left = "Open /config";\n    state = "OFFLINE";\n    stateColor = red;\n  } else if (!wx.valid) {\n    left = lastApiError.length() ? "Weather API error" : "Fetching weather...";\n    state = "OFFLINE";\n    stateColor = red;\n  } else {\n    left = "Updated " + updateClockText();\n    const bool stale = dataStale();\n    state = stale ? "STALE" : "ONLINE";\n    stateColor = stale ? red : green;\n  }\n\n  drawClockIcon(13, 147, muted);\n  display.setTextDatum(textdatum_t::middle_left);\n  display.setFont(&fonts::Font0);\n  display.setTextSize(0.74f);\n  display.setTextColor(C_WHITE);\n  display.drawString(left, 25, 147);\n\n  // Fixed left-anchored status geometry prevents ONLINE/OFFLINE from\n  // crowding or clipping against the physical right edge.\n  display.fillCircle(267, 147, 2, stateColor);\n  display.setTextDatum(textdatum_t::middle_left);\n  display.setTextSize(0.74f);\n  drawBoldText(state, 274, 147, stateColor);\n\n  if (buttonHint && buttonHint[0]) {\n    display.setTextDatum(textdatum_t::middle_center);\n    display.setTextSize(0.68f);\n    display.setTextColor(muted);\n    display.drawString(buttonHint, 160, 162);\n  }\n  display.setTextSize(1.0f);\n}\n\nvoid drawFooter()''',
    'status bar')

replace(
    r'''static void drawLandscapeApparentValue\(float apparentF\) \{.*?\n\}\n\nstatic void drawFullScreenHero\(\)''',
    '''static void drawLandscapeApparentValue(float apparentF) {\n  const String value = String((int)lroundf(apparentF));\n  const float scale = value.length() >= 3 ? 0.98f : 1.10f;\n\n  display.setTextColor(C_WHITE);\n  display.setTextDatum(textdatum_t::middle_left);\n  display.setFont(&fonts::Font7);\n  display.setTextSize(scale);\n  const int valueWidth = display.textWidth(value);\n\n  display.setFont(&fonts::Font4);\n  display.setTextSize(1.0f);\n  const int fWidth = display.textWidth("F");\n  const int groupWidth = valueWidth + 13 + fWidth;\n  const int startX = 47 + (130 - groupWidth) / 2;\n\n  display.setFont(&fonts::Font7);\n  display.setTextSize(scale);\n  display.drawString(value, startX, 88);\n\n  const int degreeX = startX + valueWidth + 2;\n  display.drawCircle(degreeX + 2, 69, 3, C_WHITE);\n  display.setFont(&fonts::Font4);\n  display.setTextSize(1.0f);\n  display.drawString("F", degreeX + 8, 90);\n}\n\nstatic void drawFullScreenHero()''',
    'apparent value')

replace(
    r'''static void drawFullScreenHero\(\) \{.*?\n\}\n\nstatic void drawDetailsScreen\(\)''',
    '''static void drawFullScreenHero() {\n  const float apparentF = apparentOutdoorF();\n  const RiskStyle risk = riskFor(apparentF);\n  const bool cold = windChillApplies();\n\n  for (int y = 0; y < 170; ++y) {\n    const float t = (float)y / 169.0f;\n    display.drawFastHLine(0, y, 320, lerp565(risk.panelTop, risk.panelBottom, t));\n  }\n\n  String station = cfg.stationName.length() ? cfg.stationName : "Weather Station";\n  if (station.length() > 16) station = station.substring(0, 16);\n  display.setTextDatum(textdatum_t::middle_left);\n  display.setFont(&fonts::Font2);\n  drawBoldText(station, 9, 14, C_WHITE);\n\n  display.setTextDatum(textdatum_t::middle_right);\n  display.setFont(&fonts::Font0);\n  display.setTextSize(0.78f);\n  display.setTextColor(rgb565(241, 247, 250));\n  display.drawString(currentDateText(), 310, 14);\n  display.setTextSize(1.0f);\n  display.drawFastHLine(8, 27, 304, risk.accent);\n\n  // Clear visual split: value on the left, risk/status on the right.\n  display.drawFastVLine(180, 35, 91, lerp565(risk.accent, C_WHITE, 0.30f));\n\n  display.setTextDatum(textdatum_t::middle_center);\n  display.setFont(&fonts::Font2);\n  drawBoldText(apparentTitle(), 112, 42, C_WHITE);\n\n  if (cold) drawHeroWind(14, 76);\n  else drawHeroSun(24, 84);\n  drawLandscapeApparentValue(apparentF);\n\n  display.setFont(&fonts::Font0);\n  display.setTextSize(0.72f);\n  display.setTextColor(rgb565(245, 249, 252));\n  display.drawString("CURRENT RISK", 249, 41);\n  display.setTextSize(1.0f);\n\n  display.fillRoundRect(188, 52, 124, 37, 18, risk.status);\n  display.drawRoundRect(188, 52, 124, 37, 18, risk.accent);\n  display.setFont(&fonts::Font4);\n  String riskLabel = apparentRiskLabel();\n  if (display.textWidth(riskLabel) > 112) {\n    display.setFont(&fonts::Font2);\n  }\n  drawBoldText(riskLabel, 250, 70, risk.accent);\n\n  display.setFont(&fonts::Font0);\n  display.setTextSize(0.78f);\n  display.setTextColor(rgb565(245, 249, 252));\n  display.drawString(cold ? "APPARENT COLD" : "APPARENT HEAT", 250, 103);\n  display.setTextSize(0.72f);\n  display.drawString("LIVE CONDITIONS", 250, 119);\n  display.setTextSize(1.0f);\n\n  drawLandscapeStatusBar("EITHER BUTTON: DETAILS");\n}\n\nstatic void drawDetailsScreen()''',
    'hero')

replace(
    r'''static void drawDetailsScreen\(\) \{.*?\n\}\n\nvoid drawWeatherScreen\(\)''',
    '''static void drawDetailsScreen() {\n  display.fillScreen(C_BLACK);\n  drawHeader();\n\n  const String temp = isfinite(wx.tempF)\n    ? String(wx.tempF, 1) + String("\\xB0") + "F" : "--";\n  const String humidity = isfinite(wx.humidity)\n    ? String((int)lroundf(wx.humidity)) + "%" : "--";\n  const String dew = isfinite(wx.dewPointF)\n    ? String(wx.dewPointF, 1) + String("\\xB0") + "F" : "--";\n  const String delta = signedTempDelta(wx.fromYesterdayF);\n\n  String wind = isfinite(wx.windMph) ? String(wx.windMph, 1) : "--";\n  wind += "/";\n  wind += isfinite(wx.gustMph) ? String(wx.gustMph, 1) : "--";\n\n  String direction = "--";\n  if (isfinite(wx.windDirDeg)) {\n    direction = directionText(wx.windDirDeg) + " " +\n      String((int)lroundf(wx.windDirDeg)) + String("\\xB0");\n  }\n\n  // Two balanced rows of four cards maximize readable type at 320x170.\n  drawLandscapeMetricCard(4, 28, 75, 48, "TEMP", temp);\n  drawLandscapeMetricCard(82, 28, 75, 48, "HUMIDITY", humidity);\n  drawLandscapeMetricCard(160, 28, 75, 48, "DEW POINT", dew);\n  drawLandscapeMetricCard(238, 28, 78, 48, "VS YDAY", delta);\n\n  drawLandscapeMetricCard(4, 79, 75, 51, "WIND/GUST", wind);\n  drawLandscapeMetricCard(82, 79, 75, 51, "DIRECTION", direction);\n  drawForecastHighLowCard();\n\n  drawLandscapeStatusBar("EITHER BUTTON: HEAT INDEX");\n}\n\nvoid drawWeatherScreen()''',
    'details')

path.write_text(text)
