[platformio]
default_envs = waveshare_7c_box

[env:waveshare_7c_box]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

lib_deps =
    moononournation/GFX Library for Arduino@1.5.1
    bblanchon/ArduinoJson@^6.21.5

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
